---
apiVersion: v1
kind: Secret
metadata:
  name: lior-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/liorjanus/lior-gitops